### ISSUE TITLE
Can't install it from the plugins list!

### ISSUE THREAD

**Issue by VitorFrost** [Pioreactor/pioreactor_custom_dosing_automation#1]
![image](https://user-images.githubusercontent.com/5491480/152389741-1a3752f7-77e8-43e6-b8cd-eb4b78ac3167.png)
I have updated from the version 22.1 to 22.2.  And I tried to install the plugin to see how it works, but I got this error. Also the folder .pioreactor/plugins don't have any new plugin!

**Comment by CamDavidsonPilon** [comment]
Closing since this is resolved
